title: Portfolio - Sree Sai Nandini Gundraju
description: My portfolio using GitHub Pages

plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-include-cache

relative_links:
  enabled: true
  collections: true

include:
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

remote_theme: pages-themes/slate



markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
